version: "3.9"

services:
  backend:
    image: wisnup001binus/bi-hackathon-backend:1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      HOST: "0.0.0.0"
      PORT: 8001
      BOOK_STORY_GENERATION_URL: "x"
      MONGODB_URL: "mongodb://mongo:27017"
      MONGODB_DB: "kanca"
      SEALION_API_KEY: "x"
      FLUX_1_SCHNELL_API_KEY: "x"
      JWT_SECRET: "secret"
      JWT_EXPIRED: 10
      GOOGLE_CLIENT_ID: "x"
      MICROSOFT_AZURE_BLOB_SAS_TOKEN: "x"
      MICROSOFT_AZURE_TEXT_TO_SPEECH_RESOURCE_KEY: "x"
    restart: always

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
